spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${pos-auth.server.url}/realms/pos-web
          jwk-set-uri: ${pos-auth.server.url}/realms/pos-web/protocol/openid-connect/certs
