pos-auth:
  server:
    url: http://pos-keycloak:8080/auth
spring:
  data:
    mongodb:
      uri: mongodb://host.docker.internal:27017/pos
pos-feign:
  applyServiceBaseUrl: "localhost:${server.port}/v1/apply/"
  agentServiceBaseUrl: "localhost:${server.port}/v1/agents/"
